apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Chart.Name }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      volumes:
      - name: php-socket
        emptyDir: {}
      - name: html
        emptyDir: {}
      - name: nginx-config-volume
        configMap:
          name: nginx-config

      initContainers:
      - name: init
        image: {{ .Values.image.name }}
        imagePullPolicy: Always
        command:
        - cp
        - "-r"
        - "/var/www/html"
        - "/"
        volumeMounts:
        - name: html
          mountPath: "/html"

      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 9000
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
{{ toYaml .Values.env | indent 8 }}
        volumeMounts:
          - name: shared-files
            mountPath: /var/www/html
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
        volumeMounts:
        - name: php-socket
          mountPath: /sock
        - name: html
          mountPath: /var/www/html

      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        command: ["/usr/sbin/nginx", "-g", "daemon off;"]
        volumeMounts:
        - name: php-socket
          mountPath: /sock
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
          readOnly: true
        - name: html
          mountPath: /var/www/html
        # readinessProbe:
        #   httpGet:
        #     path: /status.php
        #     port: 80
        #   initialDelaySeconds: 5
        #   periodSeconds: 15
        # livenessProbe:
        #   httpGet:
        #     path: /status.php
        #     port: 80
        #   initialDelaySeconds: 5
        #   periodSeconds: 15
        #   timeoutSeconds: 5
