{{- if .Values.ingress.enabled -}}

# The ConfigMap MUST be created first for the ingress controller to be able to
# find it when the Ingress object is created.

apiVersion: v1
kind: ConfigMap
metadata:
  name: fpm-cm
data:
  SCRIPT_FILENAME: "app/index.php"

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Chart.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
    nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: "fpm-cm"
spec:
  rules:
  - host: {{ .Values.basedomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "name" . }}
          servicePort: {{ .Values.service.name }}
{{- end -}}
