---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
