apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: "{{ template "name" . }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service  }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.internalPort }}
    targetPort: {{ .Values.service.internalPort }}
    name: {{ .Values.service.name }}
  selector:
    app: {{ template "name" . }}
