---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.externalPort }}
    protocol: TCP
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
